### ISSUE TITLE
TypeError: Cannot read property 'methods' of undefined

### ISSUE THREAD

**Issue by celestialcitizen** [visionmedia/express-resource#62]
Hi

I am using
Express  -- express@3.0.0beta7 and  express-resource@0.2.4 on WinXP

When I require express-resource as require('express-resource')

I get the following error

TypeError: Cannot read property 'methods' of undefined
    at Object.<anonymous> (D:\some-folder\node_modules\express-resource\index.js:234:15
)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (D:\some-folder\news-rest-server.js:7:15)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)

**Comment by celestialcitizen** [comment]
Sorry it is same as https://github.com/visionmedia/express-resource/issues/55
